# Generated by Django 4.1.7 on 2023-03-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_filme', models.CharField(max_length=100)),
                ('concluido', models.BooleanField(default=False)),
                ('resenha', models.TextField()),
            ],
        ),
    ]
